<?php
//语言配置文件
return array(
		'confirm'=>'确定',
		'cancel'=>'取消',
        'menu'=>array(
			'menu'=>'菜单管理',
			'id'=>'id',
			'name'=>'菜单名称',
			'icon'=>'图标名称',
			'desc'=>'菜单简述',
			'ctl_id'=>'控制器',
			'act_id'=>'方法名',
			'parent_id'=>'上级菜单',
			'orderby'=>'排序',
			'create_time'=>'添加时间',
		),
		'controller'=>array(
		    'controller'=>'控制器管理',
		    'id'=>'序号',
			'name'=>'控制器',
			'title'=>'名称',
			'desc'=>'描述',
		),
		'action'=>array(
		    'controller'=>'动作管理',
		    'id'=>'序号',
			'name'=>'动作',
			'title'=>'名称',
			'desc'=>'描述',
		),
);